#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
sh ~/.config/polybar/launch.sh
bspc config focus_follows_pointer true

MON=$(xrandr --listmonitors | grep Monitors | cut -b 11-)
# caso tenha, executa o setup para dois
if [[ $MON == 2 ]] ; then
	xrandr --output HDMI1 --right-of eDP1 --auto &
        bspc monitor -d 1 2 3 4 5
        bspc monitor HDMI1 -d 6 7 8 9
else
        bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
